#!/bin/bash

# set the environment
export BOOSTPATH=$(ls ${VO_CMS_SW_DIR}/${SCRAM_ARCH}/external/boost/* -d | tail -n 1)
export BOOSTLIB=${BOOSTPATH}/lib/libboost_regex.so.${BOOSTPATH/*\//}
export EXCALIBUR_BASE=$(readlink -e .)
export KAPPAPATH=$EXCALIBUR_BASE/../Kappa
export KAPPATOOLSPATH=$EXCALIBUR_BASE/../KappaTools
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$EXCALIBUR_BASE:$EXCALIBUR_BASE/../Kappa/lib:$EXCALIBUR_BASE/../KappaTools/lib:$BOOSTPATH/lib
export PATH=$EXCALIBUR_BASE/scripts:$PATH
export PYTHONPATH=$EXCALIBUR_BASE/plotting:$EXCALIBUR_BASE/plotting/tools:$EXCALIBUR_BASE/cfg/artus:$PYTHONPATH
export USERPC=`who am i | sed 's/.*(\([^]]*\)).*/\1/g'`
export SYNCDIR=${EXCALIBUR_BASE}/out/websync

# Set some user specific variables
if [ $USER = "dhaitz" ]; then
    if [ -f $EXCALIBUR_BASE/work/data.root ]; then
        export DATA=`readlink $EXCALIBUR_BASE/work/data.root`
    fi
    if [ -f $EXCALIBUR_BASE/work/mc.root ]; then
        export MC=`readlink $EXCALIBUR_BASE/work/mc.root`
    fi
    if [ $HOSTNAME = "ekpcms5" ]; then
        export EXCALIBUR_WORK=/storage/a/dhaitz/excalibur
    elif [[ $HOSTNAME == *naf* ]]; then
        export EXCALIBUR_WORK=/nfs/dust/cms/user/dhaitz
    fi
    export PATH=/home/dhaitz/git/grid-control:$PATH
elif [ $USER = "berger" ]; then
    export PATH=/home/berger/sw/bin:/home/berger/sw/grid-control:$PATH
    if [ $HOSTNAME = "ekpcms5" ]; then
        export EXCALIBUR_WORK=/storage/8/berger/excalibur
    elif [[ $HOSTNAME == *naf* ]]; then
        export EXCALIBUR_WORK=/nfs/dust/cms/user/jberger
    fi
    export DATA=/storage/8/berger/excalibur/artus/data/out.root
    export MC=/storage/8/berger/excalibur/artus/mc/out.root
fi

###artus auto-completion
function _artuscomplete_()
{
    local names
    for i in `ls ${EXCALIBUR_BASE}/cfg/artus/*.py`
        do names="${names} `basename $i .py`"
    done
    COMPREPLY=($(compgen -W "${names}" -- ${COMP_WORDS[COMP_CWORD]}))
}
complete -F _artuscomplete_ artus


# Use this to open a root file directly in the TBrowser
rot()
{
    root -l $@ $EXCALIBUR_BASE/scripts/tbrowser.cxx
}

# Use this to open the default data and mc files directly in a TBrowser
alias rooot='rot $DATA $MC'


checkKappa()
{
	cd ${EXCALIBUR_BASE}/../Kappa
	echo `git branch | sed -n '/\* /s///p'`
	cd - > /dev/null 2>&1
}
checkExcalibur()
{
	cd ${EXCALIBUR_BASE}
	echo `git branch | sed -n '/\* /s///p'`
	cd - > /dev/null 2>&1
}
switchKappa()
{
	(cd ${EXCALIBUR_BASE}/../Kappa && git checkout $1 && cd DataFormats/test/ && make -B -j && cd ../../../KappaTools &&  make -B -j)
}
switchExcalibur()
{
	(cd $EXCALIBUR_BASE && git checkout $1)
}
compileExcalibur()
{
    (cd $EXCALIBUR_BASE && make -B -j)
}
