#!/bin/bash

# set the environment
export BOOSTPATH=/wlcg/sw/boost/current/
export EXCALIBUR_BASE=$(readlink -e .)
export KAPPAPATH=$EXCALIBUR_BASE/../Kappa
export KAPPATOOLSPATH=$EXCALIBUR_BASE/../KappaTools
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$EXCALIBUR_BASE:$EXCALIBUR_BASE/../Kappa/lib:$EXCALIBUR_BASE/../KappaTools/lib:$BOOSTPATH/lib
export PATH=$EXCALIBUR_BASE/scripts:$PATH
export PYTHONPATH=$EXCALIBUR_BASE/plotting:$EXCALIBUR_BASE/cfg/artus:$PYTHONPATH
export USERPC=`who am i | sed 's/.*(\([^]]*\)).*/\1/g'`

# Set some user specific variables
if [ $USER = "dhaitz" ]; then
    if [ -f /storage/a/dhaitz/excalibur/work/data/out/artus.root ]; then
        export DATA='/storage/a/dhaitz/excalibur/work/data/out/artus.root'
    else
        export DATA='/storage/a/dhaitz/excalibur/work/data_old/out/artus.root'
    fi
    if [ -f /storage/a/dhaitz/excalibur/work/mc/out/artus.root ]; then
        export MC='/storage/a/dhaitz/excalibur/work/mc/out/artus.root'
    else
        export MC='/storage/a/dhaitz/excalibur/work/mc_old/out/artus.root'
    fi
elif [ $USER = "berger" ]; then
    export PATH=/home/berger/sw/bin:/home/berger/sw/grid-control:$PATH
    export EXCALIBUR_WORK=/storage/8/berger/excalibur
    export DATA=/storage/a/dhaitz/excalibur/work/data/out/artus.root
    export MC=/storage/a/dhaitz/excalibur/work/mc/out/artus.root
fi

alias ka='killall artus'

# plotting aliases and functions
alias plotsync='rsync $EXCALIBUR_BASE/out/plot.pdf $USER@$USERPC.physik.uni-karlsruhe.de:/usr/users/$USER/plot.pdf'

alias plot='python $EXCALIBUR_BASE/plotting/plotbase.py'
alias plott='python $EXCALIBUR_BASE/plotting/plotbase.py $DATA $MC'
alias plotfile='python $EXCALIBUR_BASE/plotting/plotbase.py $DATA $MC -o $EXCALIBUR_BASE/out/ -f pdf --filename plot'
alias plotfilemc='python $EXCALIBUR_BASE/plotting/plotbase.py $MC -o $EXCALIBUR_BASE/out/ -l 0 -f pdf --filename plot'

# Use this in combination with plotfile for live plotting
plotinit()
{
 ssh $USER@$USERPC "DISPLAY=:0 evince /usr/users/$USER/plot.pdf &" &
 export PROMPT_COMMAND="plotsync"
}

# Use this to open a root file directly in the TBrowser
rot()
{
    root -l $@ /home/$USER/tbrowser.cxx
}

# Use this to open the default data and mc files directly in a TBrowser
alias rooot='rot $DATA $MC'

