#!/bin/bash

# set the environment
export BOOSTPATH=$(ls ${VO_CMS_SW_DIR}/${SCRAM_ARCH}/external/boost/* -d | tail -n 1)
export BOOSTLIB=${BOOSTPATH}/lib/libboost_regex.so.${BOOSTPATH/*\//}
export EXCALIBUR_BASE=$(readlink -e .)
export KAPPAPATH=$EXCALIBUR_BASE/../Kappa
export KAPPATOOLSPATH=$EXCALIBUR_BASE/../KappaTools
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$EXCALIBUR_BASE:$EXCALIBUR_BASE/../Kappa/lib:$EXCALIBUR_BASE/../KappaTools/lib:$BOOSTPATH/lib
export PATH=$EXCALIBUR_BASE/scripts:$PATH
export PYTHONPATH=$EXCALIBUR_BASE/plotting:$EXCALIBUR_BASE/plotting/tools:$EXCALIBUR_BASE/cfg/artus:$PYTHONPATH
export USERPC=`who am i | sed 's/.*(\([^]]*\)).*/\1/g'`
export SYNCDIR=${EXCALIBUR_BASE}/out/websync

# Set some user specific variables
if [ $USER = "dhaitz" ]; then
    if [ -f /storage/a/dhaitz/excalibur/artus/data/out.root ]; then
        export DATA='/storage/a/dhaitz/excalibur/artus/data/out.root'
    fi
    if [ -f /storage/a/dhaitz/excalibur/artus/mc/out.root ]; then
        export MC='/storage/a/dhaitz/excalibur/artus/mc/out.root'
    fi
    export EXCALIBUR_WORK=/storage/a/dhaitz/excalibur
    export PATH=/home/dhaitz/git/grid-control:$PATH
elif [ $USER = "berger" ]; then
    export PATH=/home/berger/sw/bin:/home/berger/sw/grid-control:$PATH
    export EXCALIBUR_WORK=/storage/8/berger/excalibur
    export DATA=/storage/8/berger/excalibur/artus/data/out.root
    export MC=/storage/8/berger/excalibur/artus/mc/out.root
fi

# Use this to open a root file directly in the TBrowser
rot()
{
    root -l $@ $EXCALIBUR_BASE/scripts/tbrowser.cxx
}

# Use this to open the default data and mc files directly in a TBrowser
alias rooot='rot $DATA $MC'

